version: '3'

services:
 app:
  image: app:latest
  restart: always
  env_file:
   - ./envs/dev.env
  command: 'sh /scripts/dev.sh'

  #these volumes pass the data from your computer to the docker container
  volumes:
   - frontend:/frontend/
   - ./app:/app
   - media-files:/media-files
   - static-files:/static-files
  ports:
   - '8000:8000'
  depends_on:
   - postgres

 postgres:
  image: postgres:11
  ports:
   - '5432:5432'
  volumes:
   - postgres:/var/lib/postgresql/data
  env_file:
   - ./envs/dev.env

#these volumes create a directory in your computer so that no matter what, they will not be deleted
volumes:
 media-files:
 static-files:
 postgres:
 frontend:
