# Generated by Django 3.1.2 on 2020-10-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ManyToManyField(related_name='m2m_restaurant_cat', to='restaurants.Restaurant'),
        ),
    ]
