# Generated by Django 3.1.2 on 2020-10-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='restaurant_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_image_restaurant', to='restaurants.restaurant'),
        ),
    ]
